[build]
  base = "/"
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[functions]
  directory = "netlify/functions"